eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8085
spring:
  application:
    name: service-zuul11111
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-ribbon
    api-b:
      path: /api-b/**
      serviceId: springcloud-feign
